### ISSUE TITLE
_createDB does not take error conditions into account

### ISSUE THREAD

**Issue by kessler** [scriptoLLC/level-session-store#2]
If something is wrong (like a corrupted db) then db variable is undefined

``` javascript
this.db = level(name, opts, function(err, db) {
      var key = self.getKey(lengthKey);
      db.get(key, function(err, length) {
        length = parseInt(length, 10) || 0;
        db.put(key, length);
        self.emit('connect');
      });
    });
```

(from https://github.com/scriptoLLC/level-session-store/blob/master/index.js#L39)

**Comment by toddself** [comment]
This is published as 2.0.0 since it involves a breaking change to the API.

**Comment by kessler** [comment]
@toddself hi, just out of curiosity, why did you throw instead of emitting an error event?

**Comment by toddself** [comment]
If you can't create the level db instance to store your session data in, your sessions will fail.

It is likely you don't want your server to just log and error and continue operating without session support? (At least for our use-case not having sessions will cause all of our authenticated pages to not load).

Do you have a use for continuing to start a server with your session support disabled?  Happy to switch to an emit and handle in other logic.

**Comment by kessler** [comment]
As far as I remember error events are special when it comes to EventEmitters. If no one is listening to the error they are thrown instead: https://nodejs.org/api/events.html#events_class_events_eventemitter

Throwing an error in the callback makes it impossible to recover from it since you can't effectively try/catch it

**Comment by toddself** [comment]
The problem here is that for our use-case we do not want to start the server at all and we want to fail immediately. I could emit an error in here, and then we could listen for that error (or not) and handle it in other ways, but since we have no action other than failing and terminating, a simple `throw` suffices.

Do you have a use-case where you want the server to continue to start and run or do something else if LevelDB is unable to connect/open a database? 

Like I said I'm open to changing this, I just need to know there's a valid use-case for making it more complex

**Comment by kessler** [comment]
The main thing about this is that anyone that use this module is
effectively exposing himself to a process crash if he is not using
process.on('unchaughtException', ...)

For example, there is a set of operations I need to do before I terminate a
process due to an error, but this error is essentially uncatchable without
using the above method.
