### ISSUE TITLE
TTL and expired sessions

### ISSUE THREAD

**Issue by web-bert** [scriptoLLC/level-session-store#6]
Hi,

From reading the source it I can't see that this allows me to specify a TTL for the session, so will this clear out old sessions? If not, is this handled by express-session? I am concerned that the db will only grow in size?

Thanks

**Comment by toddself** [comment]
So this is really a two part thing.

If you're calling `destroy` on the session when the user logs out, it will delete the underlying data from the leveldb. (This is confirmed in [the test suite](https://github.com/scriptoLLC/level-session-store/blob/master/test.js#L60-L76))

If you are setting an explicit maxAge on your cookies and auto-logging people out after a certain time, express-session does not destroy the session automatically, nor does this library provide an easy provision for handling it due to limitations in how LevelDB works.

You could solve this with a custom middleware which sees the expired session and asks it to be deleted when the client returns after expiration however. 

This does expose a `clear` method though which you can use to remove all the sessions from a store, but that option is rather, well, _final_

**Comment by web-bert** [comment]
Ok, thank you for the explanation.
